### ISSUE TITLE
 Function: write_authors() (compile description authors section from CSV with author details)

### ISSUE THREAD

**Issue by larnsce** [openwashdata-dev/openwashdata#11]

**Comment by sebastian-loos** [comment]
Hey @mbannert 

I looked into your work for the authors functions. It's great!!

I was asking myself how we should proceed if the package includes several datasets and there are more than one donators. All of them would have to fill in the Authors data, which could happen over a longer period of time. 

At the moment the `usethis::use_author()` function is not able to check if a person is already located in `DESCRIPTION` and throws an error. It would be nice if there would be a function that updates the authors info. We could then rerun it every time authors information has been added to the csv-file... Maybe you want to have look into the [desc package](https://desc.r-lib.org/index.html). It has advanced options to manipulate the `DESCRIPTION` file.

@mianzg and I also went through the working process again and thought that when collaborating with multiple donators (not only then), a google sheet would be the most convenient solution for now, since GitHub doesn't offer an optimal solution for spreadsheet manipulation. A similar concern for the dictionary was mentioned by @larnsce in [this Issue](https://github.com/openwashdata/book/issues/13#issuecomment-1607294778).

Therefore I have a couple of questions.. Do you think it is possible to have a

`create_authors()` function that
- creates the authors skeleton as a google sheet in a folder of our organizations G-Drive?
- gets called initially by the `init()` function?
- automatically includes the developers (our) info to the google sheet?
 
`update_authors` function
- have an update_authors() function that fetches the information from the google sheet and adds to `DESCRIPTION`?
- Additionally, but secondary, update the `CITATION.cff` using the `cffr` package?

**Comment by sebastian-loos** [comment]
We could actually have similar functions for the dictionary-files. Since it has kind of the same workflow including the communication with the donators:)

**Comment by larnsce** [comment]
👍 for the idea of using a Google sheet. People are very used to spreadsheet manipulation in Sheets and the googlesheets4 package is very handy.

Same workflow for dictionary.csv also makes sense.

**Comment by mbannert** [comment]
We could use googlesheets down the road but we should have a basic .csv functionality that we can use asap. 
A `use_authors_from_csv` function does not prevent us from creating `use_authors_from_gsheet` in the future. I've seen the Google's APIs change more than once over the years and definitely want to have a simple, zero maintenance interface as the baseline. 

I'd rather invest the time into taking a look at our options to fix the existing-authors-issue you mention.

**Comment by larnsce** [comment]
Link: https://github.com/openwashdata/book/issues/13#issuecomment-1621165618

**Comment by mbannert** [comment]
based on a discussion with @bonschorno @mianzg: 

- @mianzg reports that adding an additional layer with Google sheets does help much, people keep sending via email. So we we shouldn't invest in a googlesheets interface here
- authors.csv is already a user interface it does not make sense to create functions to edit cells in text files. simply override the CFF based on the most recent authors
- to add a more formal submission layer, GitHub issues and issue templates, e.g., author information submission, plus using the GitHub is more promising as GitHub is our platform of choice anyway. (rather invest in working with GitHub API)
